---
title: "Experiment Name"
author: "Your Name"
output:
  html_document:
    mathjax: null
    highlight: null
    theme: null
    css: jspsych-6-2/css/jspsych.css
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
# load the plugin scripts in plugins.html which is included in the header.
```

```{r}
# load jspsych and plugin scripts
# note: this is an r code chunk
library(htmltools)
tagList(
tags$script(src='jspsych-6-2/jspsych.js'),
tags$script(src='jspsych-6-2/plugins/jspsych-html-keyboard-response.js'),
tags$script(src='jspsych-6-2/plugins/jspsych-image-keyboard-response.js'),
tags$script(src='jspsychr/jspsychr.js')
)
```

```{r, results="asis"}
# Define stimuli in R, output as script 
# note: this is an r code chunk, with results = "asis"
library(jspsychr)
library(dplyr)

# locate folders containing pictures used in original study

replication_picture_categories <- data.frame(
  folder_name = c("beach-68","underwater-68","castle-68","skyscraper-68","garden-68",
                  "stairscase-68","bedroom-68","diningroom-68","gym-68","church-inside-68",
                  "barn-68","bridge-68","woods-68","canyon-68","desert-68",
                  "greenhouse-68","lobby-68","kitchen-68","bar-68","classroom-68"),
  indoor_outdoor = c(rep("outdoor",5),rep("indoor",5),rep("outdoor",5),rep("indoor",5)),
  list = c(rep("study",10),rep("new",10))
)

# get 12 pictures from each folder
stimulus_table <- data.frame()
for(i in 1:dim(replication_picture_categories)[1]){
  #get all picture file names
  image_names <- list.files(paste0("Scenes/68-scenes/",
                                   replication_picture_categories$folder_name[i],"/"),
                            pattern = "\\.jpg$")
  
  # randomly choose 12 picture
  choose_12 <- sample(image_names,12)
  choose_12 <- paste0("Scenes/68-scenes/",
                      replication_picture_categories$folder_name[i],"/",
                      choose_12)
  
  #write temporary stimulus dataframe
  temp_stim_df <- data.frame(picture = choose_12,
                             indoor_outdoor = replication_picture_categories$indoor_outdoor[i],
                             list = replication_picture_categories$list[i]
                             )
  
  #add temporary dataframe to full stimulus dataframe
  stimulus_table <- rbind(stimulus_table,temp_stim_df)
}

# add encoding instruction as a column to simulus_table

encoding_instruction <- c(rep(rep(c("R","F"),each=6),10),rep(NA,120))
stimulus_table <- cbind(stimulus_table,encoding_instruction)

# convert df to json
stimulus_json <- stimulus_df_to_json(df = stimulus_table,
                                     stimulus = "picture",
                                     data = c("indoor_outdoor","list","encoding_instruction"))
# write json object to script
write_to_script(stimulus_json,"test_stimuli")
```


```{js}
/* Note this is a js (javascript) code chunk */

var timeline = [];

/* experiment parameters */

var reps_per_trial_type = 1;

var welcome = {
  type: "html-keyboard-response",
  stimulus: `
  <p> Welcome to the experiment, press a key to continue </p>
  `,
  post_trial_gap: 0
};

var oneimage = {
  type: "image-keyboard-response",
  stimulus: "Scenes/68-scenes/iceberg-68/_MG_4705_iceberg_500.jpg",
  post_trial_gap: 0
};

var fixation = {
  type: 'html-keyboard-response',
  stimulus: '<div style="font-size:60px;">+</div>',
  choices: jsPsych.NO_KEYS,
  trial_duration: 1000,
};

var multipleimages = {
  timeline: [fixation, {
    type: 'image-keyboard-response',
    choices: ["o","n"],
    trial_duration: 4000,
    response_allowed_while_playing: true,
    response_ends_trial: true,
    stimulus: jsPsych.timelineVariable('stimulus'),
    data: jsPsych.timelineVariable('data'),
  },
  {
  type: 'html-keyboard-response',
  stimulus: function(){
    var data = jsPsych.timelineVariable('data', true);
    var html="<p>"+ data.encoding_instruction + "</p>";
    return html;
  },
  choices: jsPsych.NO_KEYS,
  trial_duration: 1000
}],
  timeline_variables: test_stimuli,
  sample: {type: 'fixed-repetitions', size: reps_per_trial_type}
};


var end = {
  type: "html-keyboard-response",
  stimulus: `
  <p> Thanks for participating </p>
  `,
  post_trial_gap: 0
};

timeline.push(welcome);
timeline.push(oneimage);
timeline.push(multipleimages);
timeline.push(end);

jsPsych.init({
  timeline: timeline,
  on_finish: function() {
    jsPsych.data.displayData();
  }
});

```
