---
title: "Experiment Name"
author: "Your Name"
output:
  html_document:
    mathjax: null
    highlight: null
    theme: null
    css: jspsych-6-2/css/jspsych.css
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
# load the plugin scripts in plugins.html which is included in the header.
```

```{r}
# load jspsych and plugin scripts
# note: this is an r code chunk
library(htmltools)
tagList(
tags$script(src='jspsych-6-2/jspsych.js'),
tags$script(src='jspsych-6-2/plugins/jspsych-html-keyboard-response.js'),
tags$script(src='jspsych-6-2/plugins/jspsych-image-keyboard-response.js'),
tags$script(src='jspsychr/jspsychr.js')
)
```

```{r, results="asis"}
# Define stimuli in R, output as script 
# note: this is an r code chunk, with results = "asis"
library(jspsychr)
library(dplyr)
library(tidyr)

# locate folders containing pictures used in original study

replication_picture_categories <- data.frame(
  folder_name = c("beach-68","underwater-68","castle-68","skyscraper-68","garden-68",
                  "stairscase-68","bedroom-68","diningroom-68","gym-68","church-inside-68",
                  "barn-68","bridge-68","woods-68","canyon-68","desert-68",
                  "greenhouse-68","lobby-68","kitchen-68","bar-68","classroom-68"),
  indoor_outdoor = c(rep("outdoor",5),rep("indoor",5),rep("outdoor",5),rep("indoor",5)),
  list = c(rep("study",10),rep("new",10))
)

# get 12 pictures from each folder
replication_picture_categories$folder_name =  paste0("Scenes/68-scenes/",replication_picture_categories$folder_name)
beach = list.files("Scenes/68-scenes/beach-68/", pattern = "\\.jpg$")
beach = sample(beach,12)
underwater = list.files("Scenes/68-scenes/underwater-68/", pattern = "\\.jpg$")
underwater = sample(underwater,12)
castle = list.files("Scenes/68-scenes/castle-68/", pattern = "\\.jpg$")
castle = sample(castle,12)
skyscraper = list.files("Scenes/68-scenes/skyscraper-68/", pattern = "\\.jpg$")
skyscraper = sample(skyscraper,12)
garden = list.files("Scenes/68-scenes/garden-68/", pattern = "\\.jpg$")
garden = sample(garden, 12)
staircase = list.files("Scenes/68-scenes/stairscase-68/", pattern = "\\.jpg$")
staircase = sample(staircase, 12)
bedroom = list.files("Scenes/68-scenes/bedroom-68/", pattern = "\\.jpg$")
bedroom = sample(bedroom,12)
diningroom = list.files("Scenes/68-scenes/diningroom-68/", pattern = "\\.jpg$")
diningroom = sample(diningroom,12)
gym = list.files("Scenes/68-scenes/gym-68/", pattern = "\\.jpg$")
gym = sample(gym,12)
church_inside = list.files("Scenes/68-scenes/church-inside-68/", pattern = "\\.jpg$")
church_inside = sample(church_inside,12)
barn = list.files("Scenes/68-scenes/barn-68/", pattern = "\\.jpg$")
barn = sample(barn,12)
bridge = list.files("Scenes/68-scenes/bridge-68/", pattern = "\\.jpg$")
bridge = sample(bridge,12)
woods = list.files("Scenes/68-scenes/woods-68/", pattern = "\\.jpg$")
woods = sample(woods,12)
canyon = list.files("Scenes/68-scenes/canyon-68/", pattern = "\\.jpg$")
canyon = sample(canyon,12)
desert = list.files("Scenes/68-scenes/desert-68/", pattern = "\\.jpg$")
desert = sample(desert,12)
greenhouse = list.files("Scenes/68-scenes/greenhouse-68/", pattern = "\\.jpg$")
greenhouse = sample(greenhouse,12)
lobby = list.files("Scenes/68-scenes/lobby-68/", pattern = "\\.jpg$")
lobby = sample(lobby,12)
kitchen = list.files("Scenes/68-scenes/kitchen-68/", pattern = "\\.jpg$")
kitchen = sample(kitchen,12)
bar = list.files("Scenes/68-scenes/bar-68/", pattern = "\\.jpg$")
bar = sample(bar,12)
classroom = list.files("Scenes/68-scenes/classroom-68/", pattern = "\\.jpg$")
classroom = sample(classroom,12)



table = cbind(bar, barn, classroom, kitchen, lobby, greenhouse, desert, canyon, woods, church_inside, gym, diningroom, bedroom, staircase, garden, skyscraper, castle, underwater, beach, bridge)
table = pivot_longer(as.data.frame(table), bar:bridge)
table = arrange(table,group_by = name)

#Add column with encoding instructions into dataframe with 240 total pics (12 pics from each of the 20 folders)
i = replicate(20,sample(sample(c(rep("R",6),rep("F",6)))))
encoding_instructions = as.vector(i)
table_stimuli = cbind(encoding_instructions, table)

colnames(table_stimuli) <- c("encoding_instruction","category","stimulus")

table_stimuli = data.frame(table_stimuli)




#Create a data table composed 12 images from each of the 20 folders

list.files("Scenes/68-scenes/iceberg-68/", pattern = "\\.jpg$")


# load file names
image_names <- list.files("Scenes/68-scenes/iceberg-68/", pattern = "\\.jpg$")



# choose 12
choose_12 <- sample(image_names,12)
choose_12 <- paste0("Scenes/68-scenes/iceberg-68/", choose_12)

stimulus_table <- data.frame(
  stimulus = choose_12,
  category = "iceberg",
  encoding_instruction = sample(c(rep("R",6),rep("F",6)))
)

# convert df to json
stimulus_json <- stimulus_df_to_json(df = table_stimuli,
                                     stimulus = "stimulus",
                                     data = c("category","encoding_instruction"))
# write json object to script
write_to_script(stimulus_json,"test_stimuli")
```


```{js}
/* Note this is a js (javascript) code chunk */

var timeline = [];

/* experiment parameters */

var reps_per_trial_type = 1;

var welcome = {
  type: "html-keyboard-response",
  stimulus: `
  <p> Welcome to the experiment, press a key to continue </p>
  `,
  post_trial_gap: 0
};

var oneimage = {
  type: "image-keyboard-response",
  stimulus: "Scenes/68-scenes/iceberg-68/_MG_4705_iceberg_500.jpg",
  post_trial_gap: 0
};

var fixation = {
  type: 'html-keyboard-response',
  stimulus: '<div style="font-size:60px;">+</div>',
  choices: jsPsych.NO_KEYS,
  trial_duration: 1000,
};

var multipleimages = {
  timeline: [fixation, {
    type: 'image-keyboard-response',
    choices: ["o","n"],
    trial_duration: 4000,
    response_allowed_while_playing: true,
    response_ends_trial: true,
    stimulus: jsPsych.timelineVariable('stimulus'),
    data: jsPsych.timelineVariable('data'),
  },
  {
  type: 'html-keyboard-response',
  stimulus: function(){
    var data = jsPsych.timelineVariable('data', true);
    var html="<p>"+ data.encoding_instruction + "</p>";
    return html;
  },
  choices: jsPsych.NO_KEYS,
  trial_duration: 1000
}],
  timeline_variables: test_stimuli,
  sample: {type: 'fixed-repetitions', size: reps_per_trial_type}
};


var end = {
  type: "html-keyboard-response",
  stimulus: `
  <p> Thanks for participating </p>
  `,
  post_trial_gap: 0
};

timeline.push(welcome);
timeline.push(oneimage);
timeline.push(multipleimages);
timeline.push(end);

jsPsych.init({
  timeline: timeline,
  on_finish: function() {
    jsPsych.data.displayData();
  }
});

```
